modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"

[[mods]]
modId="shadows_and_pjlunas_end"
version="0.1.0"
displayName="Shadow's and Pjluna's End"
displayURL="https://modrinth.com/project/project-overide"
logoFile="logo.png"
credits="Thank you to Pjluna for helping me make this mod and testing for bugs to"
authors="ShadowB & Pjluna"
description="Shadow's and Pjluna's End MOD"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.shadows_and_pjlunas_end]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.shadows_and_pjlunas_end]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration